repos:
  - repo: local
    hooks:
      - id: absolufy-imports
        name: absolufy-imports
        stages: [commit]
        language: system
        entry: poetry run absolufy-imports
        types: [python]
      - id: ruff
        name: ruff
        stages: [commit]
        language: system
        entry: poetry run ruff check
        types: [python]
      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: poetry run mypy
        args: [--disallow-untyped-defs, --disallow-incomplete-defs, --no-implicit-optional, --local-partial-types, --strict-equality, ]
        types: [python]
        require_serial: true
